package CastApp;

/**
* CastApp/CastOnHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CastName.idl
* 15 April 2017 16:06:15 o'clock IST
*/

public final class CastOnHolder implements org.omg.CORBA.portable.Streamable
{
  public CastApp.CastOn value = null;

  public CastOnHolder ()
  {
  }

  public CastOnHolder (CastApp.CastOn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CastApp.CastOnHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CastApp.CastOnHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CastApp.CastOnHelper.type ();
  }

}
