package CastApp;


/**
* CastApp/CastOnOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CastName.idl
* 15 April 2017 16:06:15 o'clock IST
*/

public interface CastOnOperations 
{
  String CastOn ();
} // interface CastOnOperations
