package com.mycompany.castapp.CastApp;


/**
* CastApp/_CastOnImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CastName.idl
* 15 April 2017 16:06:15 o'clock IST
*/

public abstract class _CastOnImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements com.mycompany.castapp.CastApp.CastOn, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CastOnImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("CastOn", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CastApp/CastOn/CastOn
       {
         String $result = null;
         $result = this.CastOn ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CastApp/CastOn:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CastOnImplBase
