package com.mycompany.castapp.CastApp;


/**
* CastApp/CastOn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CastName.idl
* 15 April 2017 16:06:15 o'clock IST
*/

public interface CastOn extends CastOnOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CastOn
